# This guide is optimized for Vagrant 1.7 and above.
# # Although versions 1.6.x should behave very similarly, it is recommended
# # to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu-unity-xenial"

  # TODO: Do I still need this for Ubuntu?
  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  #config.ssh.password = "vagrant"

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "provisioning/playbook.yml"
  end

  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
