anyenv_repo: https://github.com/riywo/anyenv
anyenv_dir_mode: "{{ env_dir_mode }}"
anyenv_file_mode: "{{ env_file_mode }}"
anyenv_user: "{{ env_user }}"
anyenv_group: "{{ env_group }}"
anyenv_root: "{{ env_user_home }}/.anyenv"
anyenv_bin: "{{ anyenv_root }}/bin"
anyenv_envs_dir: "{{ anyenv_root }}/envs"
anyenv_ohmyzsh_config: "{{ zsh_ohmyzsh_custom_dir }}/anyenv.zsh"
