---
- name: direnv
  block:
    - name: install
      become: true
      apt:
        name: direnv
    
    - name: direnv zsh hook
      become: true
      copy:
        src: direnv.zsh
        dest: "{{ zsh_ohmyzsh_custom_dir }}/direnv.zsh"
    
    - name: directories
      file:
        path: "{{ item.key }}"
        state: directory
      loop: "{{ direnv_dirs2envrcs|dict2items }}"
    
    - name: envrcs
      copy:
        src: "{{ item.value }}"
        dest: "{{ item.key }}/.envrc"
      loop: "{{ direnv_dirs2envrcs|dict2items }}"
  tags:
    - direnv
