---
- name: apt repository
  apt_repository:
    repo: 'ppa:snwh/pulp'

- name: apt package
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - paper-icon-theme
