---
- name: theme - install
  apt: name=vivacious-colors-gtk-dark state=present update_cache=yes
  tags:
    - ravefinity

- name: theme - gtk-theme
  dconf: >
    user={{ ansible_ssh_user }}
    key=/org/gnome/desktop/interface/gtk-theme
    value="'Vivacious-Dark-Aqua'"
  notify: restart unity
  tags: ravefinity

- name: theme - window decoration theme
  dconf: >
    user={{ ansible_ssh_user }}
    key=/org/gnome/desktop/wm/preferences/theme
    value="'Vivacious-Dark-Aqua'"
  notify: restart unity
  tags: ravefinity
