---
galaxy_info:
  author: David Naughton
  description: Installs and configures Java packages.
  min_ansible_version: 2.7.5
  platforms:
  - name: Ubuntu
    versions:
    - all
dependencies:
  - role: env
  - role: zsh
