---
- name: install
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - direnv
  tags:
    - zsh

- name: install Oh My ZSH!
  shell: ZSH={{ zsh_global_oh_my_zsh_root }} sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
  tags:
    - zsh

- name: direnv hook
  become: true
  copy:
    src: direnv.zsh
    dest: "{{ zsh_global_oh_my_zsh_root }}/direnv.sh"
    owner: root
    group: root
    mode: "644"
  tags:
    - zsh

- name: install powerlevel9k theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ zsh_global_oh_my_zsh_root }}/custom/themes/powerlevel9k"
  tags:
    - zsh

- name: install syntax highlighting plugin
  git:
    repo: git://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_global_oh_my_zsh_root }}/custom/plugins/zsh-syntax-highlighting"
  tags:
    - zsh

- name: global config directory
  become: true
  file:
    path: "{{ zsh_global_config_root }}"
    state: directory
    owner: root
    group: root
    mode: "755"
  tags:
    - zsh

- name: global zshrc
  become: true
  template:
    src: global.zshrc.j2
    dest: "{{ zsh_global_config_root }}/zshrc"
    owner: root
    group: root
    mode: "644"
  tags:
    - zsh

- name: ensure global zshrc invocation
  become: true
  lineinfile:
    dest: /etc/zsh/zshrc
    line: "source {{ zsh_global_config_root }}/zshrc"
  tags:
    - zsh

- name: user zshrc
  copy:
    src: user.zshrc
    dest: /home/{{ ansible_ssh_user }}/.zshrc
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "600"
  tags:
    - zsh

- name: root zshrc
  become: true
  copy:
    src: root.zshrc
    dest: /root/.zshrc
    owner: root
    group: root
    mode: "600"
  tags:
    - zsh

- name: change login shells
  become: true
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - "{{ ansible_ssh_user }}"
    - root
  tags:
    - zsh
