---
- name: zsh
  block:
    - name: install zsh
      apt:
        name: zsh
    
    - name: set default shell
      user:
        name: "{{ zsh_default_user }}"
        shell: /bin/zsh
  become: true
  tags:
    - zsh

- name: Oh My Zsh!
  block:
    - name: oh-my-zsh installed?
      stat: path={{ zsh_ohmyzsh_root }}
      register: ohmyzsh_root
      changed_when: False

    - name: install oh-my-zsh
      shell: ZSH={{ zsh_ohmyzsh_root }} sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)" "" --unattended
      when: not ohmyzsh_root.stat.exists
    
    - name: install powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ zsh_ohmyzsh_themes_dir }}/powerlevel10k"
    
    - name: install syntax highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ zsh_ohmyzsh_plugins_dir }}/zsh-syntax-highlighting"
    
    - name: install autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ zsh_ohmyzsh_plugins_dir }}/zsh-autosuggestions"

    - name: install user config files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/{{ item }}"
      loop:
          - .zshrc
          - .p10k.zsh
  tags:
    - ohmyzsh
    - zsh
