---
galaxy_info:
  author: David Naughton
  description: Installs ntp and updates system datetime.
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  #license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.7.5
  platforms:
  - name: Ubuntu
    versions:
    - all
dependencies:
