---
- name: apt key
  become: true
  apt_key:
    url: "{{ atom_base_url }}/gpgkey"
  tags:
    - atom

- name: apt repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] {{ atom_base_url }}/any/ any main
    filename: atom
  tags:
    - atom

- name: install
  become: true
  apt:
    name: atom
  tags:
    - atom
