"" NeoBundle

" Note: Skip initialization for vim-tiny or vim-small.
if 0 | endif

if &compatible
set nocompatible               " Be iMproved
endif

" Required:
set runtimepath^=~/.vim/bundle/neobundle.vim/

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'bling/vim-airline'
" indicate the current git branch in the status line:
NeoBundle 'tpope/vim-fugitive'

NeoBundleLazy 'evidens/vim-twig', {'autoload':{'filetypes':['twig']}}

call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

"" color scheme stuff

" from http://vim.wikia.com/wiki/256_colors_in_vim
syntax enable

" This causes the text to blink in some (16-color) terminals, including Macs.
set t_Co=256

" Enforce a transparent background:
hi Normal ctermbg=NONE

"" Airline

" Always show status line.
set laststatus=2

" Automatically populate the g:airline_symbols dictionary with the powerline symbols.
let g:airline_powerline_fonts=1

" Show a tabline of open buffers.
let g:airline#extensions#tabline#enabled = 1
