---
- name: directories
  file:
    state: directory
    path: "{{ anyenv_root }}"
    owner: "{{ anyenv_user }}"
    group: "{{ anyenv_group }}"
    mode: "{{ anyenv_dir_mode }}"

- name: install
  git:
    repo: "{{ anyenv_repo }}"
    dest: "{{ anyenv_root }}"

- name: ohmyzsh config file
  become: true
  template:
    src: anyenv.zsh.j2
    dest: "{{ anyenv_ohmyzsh_config }}"
    owner: "{{ zsh_install_user }}"
    group: "{{ zsh_install_group }}"
    mode: "{{ zsh_file_mode }}"
