---
- name: anyenv
  block:
    - name: install dependencies
      become: true
      apt:
        name: "{{ anyenv_dependencies }}"
    
    - name: anyenv root
      file:
        state: directory
        path: "{{ anyenv_root }}"
    
    - name: install
      git:
        repo: "{{ anyenv_repo }}"
        dest: "{{ anyenv_root }}"
    
    - name: initialize install manifest
      git:
        repo: "{{ anyenv_install_repo }}"
        dest: "{{ anyenv_install_manifest_dir }}"
    
    - name: initialize anyenv
      ansible.builtin.shell: eval "$({{ anyenv_exe }} init -)"
      args:
        executable: /bin/zsh

    - name: ohmyzsh config file
      become: true
      template:
        src: anyenv.zsh.j2
        dest: "{{ anyenv_ohmyzsh_config }}"
    
    - name: install envs
      ansible.builtin.shell: anyenv install {{ item }}
      args:
        executable: /bin/zsh
      loop: "{{ anyenv_envs }}"
  tags:
    - anyenv
