---
- name: install packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - build-essential
    - libffi-dev
    - libssl-dev 
    - openssl
    - zlib1g-dev
  tags:
    - anyenv

- name: directories
  file:
    state: directory
    path: "{{ anyenv_root }}"
    owner: "{{ anyenv_user }}"
    group: "{{ anyenv_group }}"
    mode: "{{ anyenv_dir_mode }}"
  tags:
    - anyenv

- name: install anyenv
  git:
    repo: "{{ anyenv_repo }}"
    dest: "{{ anyenv_root }}"
  tags:
    - anyenv

- name: ohmyzsh config file
  become: true
  template:
    src: anyenv.zsh.j2
    dest: "{{ anyenv_ohmyzsh_config }}"
    owner: "{{ zsh_install_user }}"
    group: "{{ zsh_install_group }}"
    mode: "{{ zsh_file_mode }}"
  tags:
    - anyenv
