---
- name: replace sqldeveloper.sh
  become: true
  copy:
    src: sqldeveloper.sh
    dest: /opt/sqldeveloper/sqldeveloper.sh
    owner: "{{ env_user }}"
    group: "{{ env_group }}"
    mode: "{{ env_exe_mode }}"
  tags:
    - sql_developer

- name: link to sqldeveloper.sh from a PATH directory
  become: true
  file:
    src: /opt/sqldeveloper/sqldeveloper.sh
    dest: /usr/local/bin/sqldeveloper
    owner: "{{ sql_developer_user }}"
    group: "{{ sql_developer_group }}"
    state: link
  tags:
    - sql_developer

- name: desktop application file
  become: true
  copy:
    src: sqldeveloper.desktop
    dest: /usr/share/applications/sqldeveloper.desktop
    owner: "{{ sql_developer_user }}"
    group: "{{ sql_developer_group }}"
    mode: "{{ sql_developer_file_mode }}"
  tags:
    - sql_developer

- name: update desktop database
  become: true
  command: update-desktop-database
  tags:
    - sql_developer
      
