---
- name: google chrome
  block:
    - name: apt key
      apt_key:
        url: "{{ chrome_base_url }}/linux_signing_key.pub"
    
    - name: apt repository
      apt_repository:
        repo: deb [arch=amd64] {{ chrome_base_url }}/chrome/deb/ stable main
        filename: google-chrome
    
    - name: install
      apt:
        name: google-chrome-stable
  become: true
  tags:
    - chrome
