---
- name: install
  import_tasks: install.yml
  tags:
    - materia_theme

- name: gdm theme
  import_tasks: gdm_theme.yml
  tags:
    - materia_theme

- name: dconf
  import_tasks: dconf.yml
  tags:
    - materia_theme

- name: gtk settings
  import_tasks: gtk_settings.yml
  tags:
    - materia_theme
