- name: Default profile config
  dconf:
    user: "{{ ansible_ssh_user }}"
    key: /com/gexperts/Tilix/profiles/{{ tilix_default_profile_id }}/{{ item.key }}
    value: "{{ item.value }}"
  with_items:
    - { key: 'visible-name', value: "'Default'" }
    - { key: 'terminal-title', value: "'${id}: <span foreground=\"#4c82c6\">${title}</span>'" }
    - { key: 'use-theme-colors', value: "false" }
    - { key: 'background-color', value: "'#000000000000'" }
    - { key: 'foreground-color', value: "'#FFFFFFFFFFFF'" }
    - { key: 'background-transparency-percent', value: 25 }
