---
- name: focus-follow-mouse
  dconf:
    user: "{{ ansible_ssh_user }}"
    key: /com/gexperts/Tilix/{{ item.key }}
    value: "{{ item.value }}"
  with_items:
    - { key: 'focus-follow-mouse', value: "true" }
    - { key: 'copy-on-select', value: "true" }
    - { key: 'terminal-title-style', value: "'small'" }
    - { key: 'theme-variant', value: "'dark'" }
