---
galaxy_info:
  author: David Naughton
  description: Common role that sets up an environment for other roles.
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  #license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.9
  platforms:
  - name: GenericLinux
    versions:
    - all
dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
