---
- name: install
  apt: name=vim state=present
  tags:
    - vim

- name: vimrc
  copy: >
    src=vimrc
    dest=/home/{{ ansible_user }}/.vimrc
    owner={{ ansible_user }}
    group={{ ansible_user }}
    mode=0664
  tags:
    - vim

- name: .vim directory
  file: path=/home/{{ ansible_user }}/.vim state=directory
    owner={{ ansible_user }}
    group={{ ansible_user }}
    mode=0775
  tags:
    - vim

- name: NeoBundle directory
  file: path=/home/{{ ansible_user }}/.vim/bundle state=directory
    owner={{ ansible_user }}
    group={{ ansible_user }}
    mode=0775
  tags:
    - vim
    - neobundle

- name: NeoBundle git clone
  git: repo=https://github.com/Shougo/neobundle.vim dest=/home/{{ ansible_user }}/.vim/bundle/neobundle.vim
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - vim
    - neobundle

#- name: NeoBundle fix git permissions
#  file: path=/home/{{ ansible_user }}/.vim/bundle/neobundle.vim owner={{ ansible_user }} group={{ ansible_user }} state=directory recurse=yes
#  tags:
#    - vim
#    - neobundle

- name: NeoBundle install
  shell: /home/{{ ansible_user }}/.vim/bundle/neobundle.vim/bin/neoinstall
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - vim
    - neobundle
