---
- name: install packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl # for installing vim-plug
    - git
    - powerline
    - vim
  tags:
    - vim

- name: show vim_dotvimrc
  debug:
    msg: vim_dotvimrc = {{ vim_dotvimrc }}

- name: directories
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ vim_user }}"
    group: "{{ vim_user }}"
    mode: 0775
  loop:
    - vim_dotvim_dir
    - vim_autoload_dir
    - vim_plugins_dir
  tags:
    - vim

- name: .vimrc
  template:
    src: vimrc.j2
    dest: "{{ vim_dotvimrc }}"
    owner: "{{ vim_user }}"
    group: "{{ vim_user }}"
    mode: 0664
  tags:
    - vim
